### PR TITLE
update readme function #3

### PR DESCRIPTION
**Pull request by RamiroMejia**

### CODE REVIEW

**Comment by aldojasb** [comment]
Sounds good! I'm merging it.

**Comment by aldojasb** [comment]
ops, I think Gabe is the reviewer, I'm sorry haha

**Comment by gfairbro** [comment]
> ops, I think Gabe is the reviewer, I'm sorry haha

@aldojasb just add yourself as the reviewer and you can complete the merge. I will add you for merge practice 😆

**Comment by aldojasb** [comment]
hahaha thanks, Gabe! I learned one more thing today hehe :)

**Review by aldojasb — APPROVED** [review]
done

**Pull request merged**
